version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:
  inception:
    name: "inception-network"
    external: true

volumes:
  mariadb-data:
    external: true