version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    container_name: redis
    build: ./bonus/redis
    restart: unless-stopped
    networks:
      - inception
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 3

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_SUB_TITLE: ${WP_SUB_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PWD: ${WP_USER_PWD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
         - DOMAIN_NAME
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    healthcheck:
      test: curl -sf https://127.0.0.1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      wordpress:
        condition: service_healthy
  
networks:
  inception:
    name: "inception-network"
    external: true

volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATADIR}/mariadb

  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATADIR}/wordpress
