version: '3.8'

services:
  mariadb:
    image: mariadb:inception
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: mariadb-admin ping -h localhost
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_ROOT_PASSWORD

  redis:
    image: redis:inception
    container_name: redis
    build: ./requirements/bonus/redis
    restart: unless-stopped
    networks:
      - inception
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 3

  static-website:
    image: static-website:inception
    container_name: static-website
    build: ./requirements/bonus/static-website
    restart: unless-stopped
    networks:
      - inception
    healthcheck:
      test: curl --silent --fail http://localhost:8081
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:inception
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - adminer-data:/var/www/adminer
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:8000
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
      
  wordpress:
    image: wordpress:inception
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - WP_URL
      - WP_TITLE
      - WP_SUB_TITLE
      - WP_ADMIN_USER
      - WP_ADMIN_EMAIL
      - WP_ADMIN_PWD
      - WP_USER
      - WP_USER_EMAIL
      - WP_USER_PWD
      - REDIS_HOST
      - REDIS_PORT

  vsftpd:
    image: vsftpd:inception
    container_name: vsftpd
    build:
      context: ./requirements/bonus/vsftpd
      args:
        - FTP_PATH=/var/www/wordpress
        - FTP_USER
    init: true
    restart: unless-stopped
    ports:
        - "20:20"
        - "21:21"
        - "21100-21110:21100-21110"
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    healthcheck:
      test: ss --tcp --listening --numeric | grep -q ':21'
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      wordpress:
        condition: service_healthy
    environment:
      - FTP_USER
      - FTP_PWD

  monitoror:
    image: monitoror:inception
    container_name: monitoror
    build: ./requirements/bonus/monitoror
    restart: unless-stopped
    networks:
      - inception
    healthcheck:
      test: curl --silent --fail http://127.0.0.1:8080
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - MO_CONFIG=/etc/monitoror/config.json
  
  nginx:
    image: nginx:inception
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
         - DOMAIN_NAME
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - adminer-data:/var/www/adminer
      - wordpress-data:/var/www/wordpress
    healthcheck:
      test: curl --insecure --silent --fail https://127.0.0.1
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      adminer:
        condition: service_healthy
      monitoror:
        condition: service_healthy
      static-website:
        condition: service_healthy
      wordpress:
        condition: service_healthy

networks:
  inception:
    name: "inception-network"
    driver: bridge

volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATADIR}/mariadb

  adminer-data:
    name: adminer-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATADIR}/adminer

  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATADIR}/wordpress
