version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_ROOT_PASSWORD
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql

networks:
  inception:
    name: "inception-network"
    external: true

volumes:
  mariadb-data:
    external: true